### ISSUE TITLE
Please add some Readme

### ISSUE THREAD

**Issue by rubo77** [VfN-NRW/offline-ssid#3]
How did you implement this? Do I have to compile this into our gluon firmware? And which files do I have to add where? Where in gluon and where in the gateway?

**Comment by RubenKelevra** [comment]
Hey @rubo77 

> How did you implement this?
With Shellscript in a Texteditor ... well, what do you want exactly be answered?

>Do I have to compile this into our gluon firmware?
If you like to, but this Shell-Script is pretty ugly, but it is stable though. Use it if you like, but we plan to replace it with a nicer script in the long-term.

>And which files do I have to add where?
You have to add this repo as module[1], and add this package as wanted package to your site.mk[2]

[1]
-append the module "offlinessid" to GLUON_SITE_FEEDS in modules
-append the following to fetch this repo:
PACKAGES_OFFLINESSID_REPO=https://github.com/FF-NRW/offline-ssid.git
PACKAGES_OFFLINESSID_COMMIT=6c06021e5bfde2ffb708fddd5b2279e4505323da

[2] append "gluon-offline-ssid" to GLUON_SITE_PACKAGES in site.mk

Else, for 2014.4.x you'll have to add these two patches:

https://github.com/VfN-NRW/gluon/blob/2014.4.x/patches/packages/gluon/0004-backport-wlan-device-name-changes-from-master.patch
https://github.com/VfN-NRW/gluon/blob/2014.4.x/patches/packages/gluon/0010-change-uci-uris-for-ssid-to-support-offline-ssid.patch

If you use the master, the second patch is enouth.

>Where in gluon and where in the gateway?
You don't have to add anything in the gateway, everything happends in the node.

Thanks for your Ticket, will add this information to readme.

**Comment by RubenKelevra** [comment]
Readme with all informations you ask for has been created, I close this ticket for now. When something is missing, please reopen.

https://github.com/VfN-NRW/offline-ssid/blob/master/gluon-offline-ssid/README.md
